Repository LLAMATOR-Core/llamator, pull requests merged in 2024-11, with the labels that each got.

#25 add logging shutdown
  src/llamator/main.py
Labels: enhancement

#26 Add example with custom attack
  README.md
  docs/howtos.md
  examples/llamator-langchain-custom-attack.ipynb
Labels: documentation

#31 Enhance title in README and CONTRIBUTING
  CONTRIBUTING.md
  README.md
Labels: documentation, enhancement

#32 refactor LLM-as-a-judge attacks
  CONTRIBUTING.md
  docs/howtos.md
  examples/llamator-api.ipynb
  examples/llamator-langchain-custom-attack.ipynb
  examples/llamator-selenium.ipynb
  examples/llamator-telegram.ipynb
  src/llamator/attack_provider/util.py
  src/llamator/attacks/ethical_compliance.py
  src/llamator/attacks/harmful_behavior.py
  src/llamator/attacks/past_tense.py
  src/llamator/attacks/ru_ucar.py
  src/llamator/attacks/ucar.py
  src/llamator/attacks/utils.py
  tests/test_llamator.py
  tests/test_local_llamator.py
Labels: bug, enhancement, invalid, question

#33 add new sycophancy test and `are_responses_coherent()` method
  src/llamator/attack_provider/util.py
  src/llamator/attacks/attack_descriptions.json
  src/llamator/attacks/sycophancy.py
Labels: enhancement

#34 fix sycophancy system prompt and description
  src/llamator/attacks/attack_descriptions.json
  src/llamator/attacks/sycophancy.py
Labels: invalid

#37 add logical inconsistencies test
  examples/llamator-api.ipynb
  examples/llamator-langchain-custom-attack.ipynb
  examples/llamator-selenium.ipynb
  examples/llamator-telegram.ipynb
  src/llamator/attack_provider/attack_loader.py
  src/llamator/attacks/attack_descriptions.json
  src/llamator/attacks/logical_inconsistencies.py
  src/llamator/initial_validation.py
Labels: enhancement

#35 corrected dan attack
  examples/llamator-telegram.ipynb
  src/llamator/attack_data/ucar-dan_prompts.parquet
  src/llamator/attacks/dan.py
  src/llamator/attacks/ru_dan.py
  src/llamator/attacks/ru_ucar.py
  src/llamator/attacks/ucar.py
Labels: bug
