Repository LLAMATOR-Core/llamator, pull requests merged in 2024-12, with the labels that each got.

#44 add fitting datasets to `num_attempts`
  src/llamator/attacks/base64_injection.py
  src/llamator/attacks/dan.py
  src/llamator/attacks/ethical_compliance.py
  src/llamator/attacks/harmful_behavior.py
  src/llamator/attacks/past_tense.py
  src/llamator/attacks/ru_dan.py
  src/llamator/attacks/ru_ucar.py
  src/llamator/attacks/ucar.py
Labels: enhancement, invalid

#50 rewrite all examples notebooks in english
  README.md
  docs/howtos.md
  examples/llamator-api.ipynb
  examples/llamator-langchain-custom-attack.ipynb
  examples/llamator-selenium.ipynb
  examples/llamator-telegram.ipynb
  examples/llamator-whatsapp.ipynb
Labels: documentation, enhancement

#52 fix attack model system prompt
  examples/llamator-api.ipynb
  examples/llamator-langchain-custom-attack.ipynb
  examples/llamator-selenium.ipynb
  examples/llamator-telegram.ipynb
  examples/llamator-whatsapp.ipynb
Labels: documentation

#54 Refactor sycophancy and logical_inconsistencies and linguistic
  CONTRIBUTING.md
  docs/attack_descriptions.md
  docs/howtos.md
  examples/llamator-api.ipynb
  examples/llamator-langchain-custom-attack.ipynb
  examples/llamator-selenium.ipynb
  examples/llamator-telegram.ipynb
  examples/llamator-whatsapp.ipynb
  src/llamator/attack_provider/attack_loader.py
  src/llamator/attacks/attack_descriptions.json
  src/llamator/attacks/linguistic.py
  src/llamator/attacks/logical_inconsistencies.py
  src/llamator/attacks/sycophancy.py
  src/llamator/initial_validation.py
  src/llamator/main.py
  tests/test_llamator.py
  tests/test_local_llamator.py
Labels: documentation, invalid

#56 enhance whatsapp example
  .gitignore
  examples/llamator-whatsapp.ipynb
Labels: documentation, enhancement

#53 Multistage attack (harmful_behavior_multistage)
  docs/attack_descriptions.md
  examples/llamator-whatsapp.ipynb
  src/llamator/attack_provider/attack_loader.py
  src/llamator/attacks/attack_descriptions.json
  src/llamator/attacks/harmful_behavior_multistage.py
  src/llamator/client/chat_client.py
  src/llamator/initial_validation.py
  src/llamator/main.py
Labels: enhancement
