Repository LLAMATOR-Core/llamator, pull requests merged in 2025-02, with the labels that each got.

#77 Docker example
  .gitignore
  README.md
  docker/Dockerfile
  docker/instruction.md
  docker/jupyter_docker.sh
  docs/howtos.md
Labels: enhancement

#78 fix bon paper and add paper for sycophancy
  docs/attack_descriptions.md
  src/llamator/attacks/bon.py
  src/llamator/attacks/sycophancy.py
Labels: documentation, invalid

#79 Harmful warning
  src/llamator/attacks/bon.py
  src/llamator/attacks/crecsendo.py
  src/llamator/attacks/sycophancy.py
  src/llamator/main.py
  tests/test_llamator.py
  tests/test_local_llamator.py
Labels: documentation, enhancement

#81 Release v2.1.0
  .bumpversion.cfg
  README.md
  docs/howtos.md
  src/llamator/__version__.py
  src/llamator/main.py
  tests/test_local_llamator.py
Labels: dependencies

#82 Suffix
  docs/attack_descriptions.md
  src/llamator/attack_data/suffixes.parquet
  src/llamator/attack_provider/attack_loader.py
  src/llamator/attacks/attack_descriptions.json
  src/llamator/attacks/suffix.py
  src/llamator/initial_validation.py
  src/llamator/main.py
Labels: documentation, enhancement

#83 Add SPL prompts
  src/llamator/attack_data/system_prompt_leakage.parquet
Labels: enhancement

#84 Small fix
  CONTRIBUTING.md
  README.md
  docker/README.md
  docs/attack_descriptions.md
  docs/howtos.md
  docs/project_overview.md
  examples/llamator-api.ipynb
  examples/llamator-selenium.ipynb
  examples/llamator-telegram.ipynb
  examples/llamator-whatsapp.ipynb
  src/llamator/attacks/suffix.py
  tests/test_llamator.py
  tests/test_local_llamator.py
Labels: documentation, improvement, invalid

#87 Release v2.2.0
  .bumpversion.cfg
  README.md
  docker/instruction.md
  docs/howtos.md
  src/llamator/__version__.py
Labels: dependencies

#88 Add Logo and `ChatSession` Exception Handling + Fix Docs
  README.md
  assets/LLAMATOR.svg
  docker/instruction.md
  docs/howtos.md
  docs/project_overview.md
  examples/llamator-api.ipynb
  examples/llamator-langchain-custom-attack.ipynb
  examples/llamator-selenium.ipynb
  examples/llamator-telegram.ipynb
  examples/llamator-whatsapp.ipynb
  src/llamator/attack_provider/util.py
  src/llamator/attacks/aim.py
  src/llamator/attacks/complimentary_transition.py
  src/llamator/attacks/crecsendo.py
  src/llamator/attacks/ethical_compliance.py
  src/llamator/attacks/harmful_behavior_multistage.py
  src/llamator/attacks/linguistic.py
  src/llamator/attacks/logical_inconsistencies.py
  src/llamator/attacks/sycophancy.py
  src/llamator/attacks/system_prompt_leakage.py
  src/llamator/client/chat_client.py
  src/llamator/client/client_config.py
  tests/test_llamator.py
  tests/test_local_llamator.py
Labels: bug, documentation, enhancement, invalid

#90 unify the language
  assets/LLAMATOR.svg
  docs/conf.py
  src/llamator/attack_provider/run_tests.py
  src/llamator/attacks/linguistic.py
  src/llamator/report_generators/word_report_generator.py
  tests/test_llamator.py
  tests/test_local_llamator.py
Labels: invalid
