Repository LLAMATOR-Core/llamator, pull requests merged in 2025-05, with the labels that each got.

#106 Implement M-Attack for VLMs
  .gitignore
  docs/attack_descriptions.md
  examples/llamator-vlm-attacks.ipynb
  pyproject.toml
  requirements-dev.txt
  setup.cfg
  src/llamator/attack_data/vlm_m_attack/.gitignore
  src/llamator/attack_data/vlm_m_attack/__init__.py
  src/llamator/attack_data/vlm_m_attack/data_download.py
  src/llamator/attack_data/vlm_m_attack_prepared.parquet
  src/llamator/attack_provider/attack_loader.py
  src/llamator/attack_provider/image_utils.py
  src/llamator/attacks/vlm_m_attack.py
  src/llamator/client/chat_client.py
Labels: enhancement, new attack

#107 Implement VLM text hallucination attack
  docs/attack_descriptions.md
  pyproject.toml
  requirements-dev.txt
  setup.cfg
  src/llamator/attack_data/text_image/.gitignore
  src/llamator/attack_data/text_image/txt/instructions.txt
  src/llamator/attack_data/text_image/txt/objects.txt
  src/llamator/attack_provider/attack_loader.py
  src/llamator/attack_provider/image_utils.py
  src/llamator/attacks/vlm_text_hallucination.py
Labels: enhancement, new attack

#108 Implement VLM low-resolution docs attack
  docs/attack_descriptions.md
  pyproject.toml
  requirements-dev.txt
  setup.cfg
  src/llamator/attack_data/lowres_pdf/.gitignore
  src/llamator/attack_provider/attack_loader.py
  src/llamator/attack_provider/image_utils.py
  src/llamator/attacks/vlm_lowres_docs.py
Labels: enhancement, new attack

#133 Add deceptive delight attack
  docs/attack_descriptions.md
  src/llamator/attack_data/deceptive_delight.parquet
  src/llamator/attack_provider/attack_loader.py
  src/llamator/attacks/deceptive_delight.py
Labels: documentation, enhancement, new attack

#131 mini refactor all attacks
  CONTRIBUTING.md
  docs/attack_descriptions.md
  examples/llamator-langchain-custom-attack.ipynb
  examples/llamator-vlm-attacks.ipynb
  pyproject.toml
  requirements-dev.txt
  setup.cfg
  src/llamator/attack_data/vlm_m_attack/data_download.py
  src/llamator/attack_provider/attack_loader.py
  src/llamator/attack_provider/test_base.py
  src/llamator/attacks/aim.py
  src/llamator/attacks/autodan_turbo.py
  src/llamator/attacks/base64_injection.py
  src/llamator/attacks/bon.py
  src/llamator/attacks/complimentary_transition.py
  src/llamator/attacks/crecsendo.py
  src/llamator/attacks/dan.py
  src/llamator/attacks/deceptive_delight.py
  src/llamator/attacks/dialogue_injection_continuation.py
  src/llamator/attacks/dialogue_injection_devmode.py
  src/llamator/attacks/ethical_compliance.py
  src/llamator/attacks/harmful_behavior.py
  src/llamator/attacks/linguistic.py
  src/llamator/attacks/logical_inconsistencies.py
  src/llamator/attacks/pair.py
  src/llamator/attacks/past_tense.py
  src/llamator/attacks/ru_dan.py
  src/llamator/attacks/ru_typoglycemia.py
  src/llamator/attacks/ru_ucar.py
  src/llamator/attacks/shuffle.py
  src/llamator/attacks/suffix.py
  src/llamator/attacks/sycophancy.py
  src/llamator/attacks/system_prompt_leakage.py
  src/llamator/attacks/typoglycemia.py
  src/llamator/attacks/ucar.py
  src/llamator/attacks/vlm_lowres_docs.py
  src/llamator/attacks/vlm_m_attack.py
  src/llamator/attacks/vlm_text_hallucination.py
  src/llamator/client/client_config.py
Labels: documentation, improvement, invalid, dependencies

#134 add VLM example to README and docs + update unique features
  README.md
  docs/howtos.md
  docs/project_overview.md
  examples/llamator-langchain-custom-attack.ipynb
  examples/llamator-vlm-attacks.ipynb
  setup.cfg
Labels: documentation

#135 remove foolish attacks
  docs/attack_descriptions.md
  src/llamator/attack_provider/attack_loader.py
  src/llamator/attacks/complimentary_transition.py
  src/llamator/attacks/ru_typoglycemia.py
  src/llamator/attacks/typoglycemia.py
Labels: documentation, invalid

#137 Dataset rework & Language customization
  docs/attack_descriptions.md
  examples/fix-jupyter.sh
  examples/llamator-api.ipynb
  examples/llamator-langchain-custom-attack.ipynb
  examples/llamator-selenium.ipynb
  examples/llamator-telegram.ipynb
  examples/llamator-vlm-attacks.ipynb
  examples/llamator-whatsapp.ipynb
  src/llamator/attack_data/harmbench_text.parquet
  src/llamator/attack_data/harmful_behavior.parquet
  src/llamator/attack_data/ucar-dan_prompts.parquet
  src/llamator/attack_provider/attack_loader.py
  src/llamator/attack_provider/test_base.py
  src/llamator/attack_provider/util.py
  src/llamator/attacks/autodan_turbo.py
  src/llamator/attacks/base64_injection.py
  src/llamator/attacks/bon.py
  src/llamator/attacks/crecsendo.py
  src/llamator/attacks/dan.py
  src/llamator/attacks/dialogue_injection_continuation.py
  src/llamator/attacks/dialogue_injection_devmode.py
  src/llamator/attacks/ethical_compliance.py
  src/llamator/attacks/harmbench.py
  src/llamator/attacks/harmful_behavior.py
  src/llamator/attacks/pair.py
  src/llamator/attacks/ru_ucar.py
  src/llamator/attacks/shuffle.py
  src/llamator/attacks/system_prompt_leakage.py
  src/llamator/attacks/ucar.py
  src/llamator/utils/test_presets.py
Labels: improvement, question

#139 Returning dict with results in the start_testing function
  README.dev.md
  src/llamator/attack_provider/run_tests.py
  src/llamator/attacks/pair.py
  src/llamator/main.py
Labels: enhancement

#140 Update Presets
  README.dev.md
  src/llamator/initial_validation.py
  src/llamator/utils/params_example.py
  src/llamator/utils/test_presets.py
Labels: improvement

#142 Update example and documentation
  docs/howtos.md
  examples/llamator-api.ipynb
  examples/llamator-langchain-custom-attack.ipynb
  examples/llamator-selenium.ipynb
  examples/llamator-telegram.ipynb
  examples/llamator-vlm-attacks.ipynb
  examples/llamator-whatsapp.ipynb
  src/llamator/attack_provider/run_tests.py
  src/llamator/attacks/vlm_m_attack.py
  src/llamator/client/chat_client.py
  src/llamator/client/client_config.py
  src/llamator/main.py
Labels: documentation, improvement
