Repository LLAMATOR-Core/llamator, pull requests merged in 2025-07, with the labels that each got.

#152 Update README.md
  README.md
  docs/project_overview.md
Labels: documentation

#151 Transform Static Past Tense Attack into Dynamic Time Machine Attack
  docs/attack_descriptions.md
  src/llamator/attack_data/past_tense.parquet
  src/llamator/attack_provider/attack_loader.py
  src/llamator/attacks/past_tense.py
  src/llamator/attacks/time_machine.py
  src/llamator/utils/params_example.py
  src/llamator/utils/test_presets.py
Labels: enhancement

#147 Add Jugde model to System Prompt Leakage attack
  src/llamator/attack_provider/util.py
  src/llamator/attacks/crecsendo.py
  src/llamator/attacks/pair.py
  src/llamator/attacks/system_prompt_leakage.py
  src/llamator/client/chat_client.py
Labels: enhancement

#153 Add contact information and enterprise version note to README.md
  README.md
Labels: documentation

#155 Add Linguistic Sandwich Attack
  docs/attack_descriptions.md
  src/llamator/attack_provider/attack_loader.py
  src/llamator/attack_provider/util.py
  src/llamator/attacks/autodan_turbo.py
  src/llamator/attacks/bon.py
  src/llamator/attacks/dialogue_injection_continuation.py
  src/llamator/attacks/dialogue_injection_devmode.py
  src/llamator/attacks/harmbench.py
  src/llamator/attacks/linguistic_sandwich.py
  src/llamator/attacks/pair.py
  src/llamator/attacks/shuffle.py
  src/llamator/attacks/suffix.py
  src/llamator/attacks/vlm_m_attack.py
Labels: enhancement, new attack

#162 Enhance evaluations
  src/llamator/attack_provider/util.py
  src/llamator/attacks/linguistic_sandwich.py
Labels: invalid

#161 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#157 Release v3.3.0
  .bumpversion.cfg
  CONTRIBUTING.md
  README.md
  docs/attack_descriptions.md
  docs/code_documentation.rst
  docs/howtos.md
  docs/project_overview.md
  examples/llamator-api.ipynb
  examples/llamator-langchain-custom-attack.ipynb
  examples/llamator-selenium.ipynb
  examples/llamator-telegram.ipynb
  examples/llamator-vlm-attacks.ipynb
  examples/llamator-whatsapp.ipynb
  setup.cfg
  src/llamator/__init__.py
  src/llamator/__version__.py
  src/llamator/attack_data/past_tense.parquet
  src/llamator/attack_provider/attack_loader.py
  src/llamator/attack_provider/util.py
  src/llamator/attacks/aim.py
  src/llamator/attacks/autodan_turbo.py
  src/llamator/attacks/base64_injection.py
  src/llamator/attacks/bon.py
  src/llamator/attacks/crecsendo.py
  src/llamator/attacks/dan.py
  src/llamator/attacks/deceptive_delight.py
  src/llamator/attacks/dialogue_injection_continuation.py
  src/llamator/attacks/dialogue_injection_devmode.py
  src/llamator/attacks/ethical_compliance.py
  src/llamator/attacks/harmbench.py
  src/llamator/attacks/linguistic.py
  src/llamator/attacks/linguistic_sandwich.py
  src/llamator/attacks/logical_inconsistencies.py
  src/llamator/attacks/pair.py
  src/llamator/attacks/past_tense.py
  src/llamator/attacks/shuffle.py
  src/llamator/attacks/suffix.py
  src/llamator/attacks/sycophancy.py
  src/llamator/attacks/system_prompt_leakage.py
  src/llamator/attacks/time_machine.py
  src/llamator/attacks/ucar.py
  src/llamator/attacks/vlm_lowres_docs.py
  src/llamator/attacks/vlm_m_attack.py
  src/llamator/attacks/vlm_text_hallucination.py
  src/llamator/client/chat_client.py
  src/llamator/initial_validation.py
  src/llamator/utils/attack_params.py
  src/llamator/utils/test_presets.py
  tests/__init__.py
  tests/get_config_example.py
  tests/get_langchain_client.py
  tests/langchain_client_test.py
  tests/openai_client_lm_studio_test.py
  tests/openai_client_mistral_test.py
  tests/print_langchain_client_test.py
  tests/print_test_preset_test.py
Labels: release
