Repository LLAMATOR-Core/llamator, pull requests merged in 2025-04, with the labels that each got.

#112 add tags
  docs/attack_descriptions.md
  src/llamator/attacks/aim.py
  src/llamator/attacks/base64_injection.py
  src/llamator/attacks/bon.py
  src/llamator/attacks/complimentary_transition.py
  src/llamator/attacks/crecsendo.py
  src/llamator/attacks/dan.py
  src/llamator/attacks/ethical_compliance.py
  src/llamator/attacks/harmful_behavior.py
  src/llamator/attacks/harmful_behavior_multistage.py
  src/llamator/attacks/linguistic.py
  src/llamator/attacks/logical_inconsistencies.py
  src/llamator/attacks/past_tense.py
  src/llamator/attacks/ru_dan.py
  src/llamator/attacks/ru_typoglycemia.py
  src/llamator/attacks/ru_ucar.py
  src/llamator/attacks/shuffle.py
  src/llamator/attacks/suffix.py
  src/llamator/attacks/sycophancy.py
  src/llamator/attacks/system_prompt_leakage.py
  src/llamator/attacks/typoglycemia.py
  src/llamator/attacks/ucar.py
Labels: documentation, enhancement

#111 v3: refactor all attacks
  docs/attack_descriptions.md
  src/llamator/attack_data/system_prompt_leakage.parquet
  src/llamator/attack_provider/test_base.py
  src/llamator/attack_provider/util.py
  src/llamator/attacks/aim.py
  src/llamator/attacks/base64_injection.py
  src/llamator/attacks/bon.py
  src/llamator/attacks/complimentary_transition.py
  src/llamator/attacks/crecsendo.py
  src/llamator/attacks/dan.py
  src/llamator/attacks/ethical_compliance.py
  src/llamator/attacks/harmful_behavior.py
  src/llamator/attacks/harmful_behavior_multistage.py
  src/llamator/attacks/linguistic.py
  src/llamator/attacks/logical_inconsistencies.py
  src/llamator/attacks/past_tense.py
  src/llamator/attacks/ru_dan.py
  src/llamator/attacks/ru_typoglycemia.py
  src/llamator/attacks/ru_ucar.py
  src/llamator/attacks/shuffle.py
  src/llamator/attacks/suffix.py
  src/llamator/attacks/sycophancy.py
  src/llamator/attacks/system_prompt_leakage.py
  src/llamator/attacks/typoglycemia.py
  src/llamator/attacks/ucar.py
  src/llamator/report_generators/excel_report_generator.py
  src/llamator/utils/test_presets.py
  tests/openai_client_lm_studio_test.py
Labels: improvement, enhancement, invalid

#117 actualize examples
  examples/llamator-api.ipynb
  examples/llamator-langchain-custom-attack.ipynb
  examples/llamator-selenium.ipynb
  examples/llamator-telegram.ipynb
  examples/llamator-whatsapp.ipynb
Labels: documentation

#121 Small improvements
  README.md
  docs/code_documentation.rst
  docs/howtos.md
  docs/project_overview.md
  src/llamator/initial_validation.py
  src/llamator/main.py
  src/llamator/utils/params_example.py
Labels: documentation, improvement, enhancement

#118 Add autodan turbo
  docs/attack_descriptions.md
  src/llamator/attack_provider/attack_loader.py
  src/llamator/attacks/autodan_turbo.py
Labels: enhancement, new attack

#113 Implement dialogue injection attack
  docs/attack_descriptions.md
  src/llamator/attack_provider/attack_loader.py
  src/llamator/attacks/dialogue_injection.py
Labels: enhancement, new attack

#124 Update attack_descriptions.md
  docs/attack_descriptions.md
Labels: documentation, invalid

#123 Change fastparquet to pyarrow
  requirements-dev.txt
  setup.cfg
  src/llamator/attacks/autodan_turbo.py
  src/llamator/attacks/base64_injection.py
  src/llamator/attacks/bon.py
  src/llamator/attacks/crecsendo.py
  src/llamator/attacks/dan.py
  src/llamator/attacks/dialogue_injection.py
  src/llamator/attacks/ethical_compliance.py
  src/llamator/attacks/harmful_behavior.py
  src/llamator/attacks/harmful_behavior_multistage.py
  src/llamator/attacks/past_tense.py
  src/llamator/attacks/ru_dan.py
  src/llamator/attacks/ru_typoglycemia.py
  src/llamator/attacks/ru_ucar.py
  src/llamator/attacks/shuffle.py
  src/llamator/attacks/suffix.py
  src/llamator/attacks/system_prompt_leakage.py
  src/llamator/attacks/ucar.py
Labels: dependencies

#125 Bump version to 3.1.0
  .bumpversion.cfg
  README.md
  docs/howtos.md
  src/llamator/__version__.py
Labels: dependencies

#126 Release v3.1.0
  .bumpversion.cfg
  README.md
  docs/attack_descriptions.md
  docs/code_documentation.rst
  docs/howtos.md
  docs/project_overview.md
  requirements-dev.txt
  setup.cfg
  src/llamator/__version__.py
  src/llamator/attack_provider/attack_loader.py
  src/llamator/attacks/autodan_turbo.py
  src/llamator/attacks/base64_injection.py
  src/llamator/attacks/bon.py
  src/llamator/attacks/crecsendo.py
  src/llamator/attacks/dan.py
  src/llamator/attacks/dialogue_injection.py
  src/llamator/attacks/ethical_compliance.py
  src/llamator/attacks/harmful_behavior.py
  src/llamator/attacks/harmful_behavior_multistage.py
  src/llamator/attacks/past_tense.py
  src/llamator/attacks/ru_dan.py
  src/llamator/attacks/ru_typoglycemia.py
  src/llamator/attacks/ru_ucar.py
  src/llamator/attacks/shuffle.py
  src/llamator/attacks/suffix.py
  src/llamator/attacks/system_prompt_leakage.py
  src/llamator/attacks/ucar.py
  src/llamator/initial_validation.py
  src/llamator/main.py
  src/llamator/utils/params_example.py
Labels: release

#129 Pair scoring enhance
  src/llamator/attacks/pair.py
Labels: enhancement
