Repository LLAMATOR-Core/llamator, pull requests merged in 2025-09, with the labels that each got.

#172 Refactor test preset functions to improve clarity.
  docs/howtos.md
  src/llamator/utils/test_presets.py
Labels: enhancement

#166 Add DoS Repetition Token Attack
  README.md
  docs/attack_descriptions.md
  docs/howtos.md
  docs/project_overview.md
  src/llamator/attack_provider/attack_loader.py
  src/llamator/attacks/repetition_token.py
Labels: documentation, enhancement, new attack

#170 Add Composition of Principles attack
  docs/attack_descriptions.md
  src/llamator/attack_provider/attack_loader.py
  src/llamator/attacks/autodan_turbo.py
  src/llamator/attacks/cop.py
  src/llamator/attacks/crecsendo.py
  src/llamator/attacks/logical_inconsistencies.py
  src/llamator/attacks/pair.py
  src/llamator/attacks/sycophancy.py
  src/llamator/attacks/system_prompt_leakage.py
  src/llamator/client/chat_client.py
Labels: enhancement, new attack

#173 fix notebooks and docs (also closes #171)
  docs/howtos.md
  examples/fix-jupyter.sh
  examples/llamator-api.ipynb
  examples/llamator-langchain-custom-attack.ipynb
  examples/llamator-selenium.ipynb
  examples/llamator-telegram.ipynb
  examples/llamator-vlm-attacks.ipynb
  examples/llamator-whatsapp.ipynb
  setup.cfg
  src/llamator/attacks/system_prompt_leakage.py
  src/llamator/utils/test_presets.py
Labels: documentation, invalid

#175 Bump version to v3.4.0
  .bumpversion.cfg
  README.md
  docs/howtos.md
  examples/llamator-api.ipynb
  examples/llamator-langchain-custom-attack.ipynb
  examples/llamator-selenium.ipynb
  examples/llamator-telegram.ipynb
  examples/llamator-vlm-attacks.ipynb
  examples/llamator-whatsapp.ipynb
  src/llamator/__version__.py
Labels: release
