Repository LLAMATOR-Core/llamator, pull requests merged in 2025-01, with the labels that each got.

#61 harmful_behavior_multistage correction
  src/llamator/attacks/harmful_behavior_multistage.py
Labels: bug, invalid

#60 Multistage depth
  CONTRIBUTING.md
  README.md
  docs/attack_descriptions.md
  docs/code_documentation.rst
  docs/conf.py
  docs/howtos.md
  docs/index.rst
  docs/project_overview.md
  examples/llamator-api.ipynb
  examples/llamator-langchain-custom-attack.ipynb
  examples/llamator-selenium.ipynb
  examples/llamator-telegram.ipynb
  examples/llamator-whatsapp.ipynb
  src/llamator/attack_provider/attack_registry.py
  src/llamator/attack_provider/run_tests.py
  src/llamator/attack_provider/test_base.py
  src/llamator/attacks/aim.py
  src/llamator/attacks/attack_descriptions.json
  src/llamator/attacks/base64_injection.py
  src/llamator/attacks/complimentary_transition.py
  src/llamator/attacks/dan.py
  src/llamator/attacks/ethical_compliance.py
  src/llamator/attacks/harmful_behavior.py
  src/llamator/attacks/harmful_behavior_multistage.py
  src/llamator/attacks/linguistic.py
  src/llamator/attacks/logical_inconsistencies.py
  src/llamator/attacks/past_tense.py
  src/llamator/attacks/ru_dan.py
  src/llamator/attacks/ru_typoglycemia.py
  src/llamator/attacks/ru_ucar.py
  src/llamator/attacks/sycophancy.py
  src/llamator/attacks/system_prompt_leakage.py
  src/llamator/attacks/typoglycemia.py
  src/llamator/attacks/ucar.py
  src/llamator/client/chat_client.py
  src/llamator/main.py
  tests/test_llamator.py
  tests/test_local_llamator.py
Labels: documentation, improvement, enhancement

#62 Add more info to attacks docs
  CONTRIBUTING.md
  docs/attack_descriptions.md
  examples/llamator-api.ipynb
  examples/llamator-langchain-custom-attack.ipynb
  examples/llamator-selenium.ipynb
  examples/llamator-telegram.ipynb
  examples/llamator-whatsapp.ipynb
  src/llamator/client/chat_client.py
Labels: documentation, enhancement

#66 Merge release v2.0.0 to main
  .bumpversion.cfg
  README.md
  docs/howtos.md
  examples/llamator-selenium.ipynb
  src/llamator/__version__.py
Labels: dependencies

#67 Release v2.0.1
  .bumpversion.cfg
  README.md
  docs/howtos.md
  docs/project_overview.md
  src/llamator/__version__.py
  src/llamator/attack_provider/util.py
  src/llamator/attacks/harmful_behavior_multistage.py
  src/llamator/attacks/past_tense.py
  src/llamator/attacks/system_prompt_leakage.py
  src/llamator/client/chat_client.py
Labels: release

#68 Update main to v2.0.1
  .bumpversion.cfg
  README.md
  docs/howtos.md
  src/llamator/__version__.py
Labels: dependencies

#70 added BON attack
  CONTRIBUTING.md
  docs/attack_descriptions.md
  docs/howtos.md
  src/llamator/attack_provider/attack_loader.py
  src/llamator/attacks/attack_descriptions.json
  src/llamator/attacks/bon.py
  src/llamator/initial_validation.py
  src/llamator/main.py
  tests/test_llamator.py
  tests/test_local_llamator.py
Labels: enhancement

#69 enhance attack sysprompt for prompt leakage and add new examples
  src/llamator/attack_data/system_prompt_leakage.parquet
  src/llamator/attacks/system_prompt_leakage.py
  src/llamator/client/chat_client.py
Labels: enhancement

#73 fix logging
  src/llamator/logging.py
  src/llamator/main.py
Labels: invalid

#76 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#72 Crescendo
  docs/attack_descriptions.md
  src/llamator/attack_provider/attack_loader.py
  src/llamator/attacks/attack_descriptions.json
  src/llamator/attacks/base64_injection.py
  src/llamator/attacks/bon.py
  src/llamator/attacks/crecsendo.py
  src/llamator/attacks/dan.py
  src/llamator/attacks/ethical_compliance.py
  src/llamator/attacks/harmful_behavior.py
  src/llamator/attacks/harmful_behavior_multistage.py
  src/llamator/attacks/past_tense.py
  src/llamator/attacks/ru_dan.py
  src/llamator/attacks/ru_ucar.py
  src/llamator/attacks/system_prompt_leakage.py
  src/llamator/attacks/ucar.py
  src/llamator/initial_validation.py
  src/llamator/main.py
  tests/test_llamator.py
  tests/test_local_llamator.py
Labels: enhancement
