Repository LLAMATOR-Core/llamator, pull requests merged in 2025-03, with the labels that each got.

#94 Release v2.3.0
  .bumpversion.cfg
  README.md
  assets/LL.svg
  assets/LLAMATOR.svg
  docs/attack_descriptions.md
  docs/conf.py
  docs/guides.rst
  docs/howtos.md
  docs/index.rst
  src/llamator/__version__.py
Labels: documentation, enhancement, dependencies

#95 Release v2.3.1
  .bumpversion.cfg
  README.md
  assets/LL.svg
  assets/LLAMATOR.svg
  docker/instruction.md
  docs/attack_descriptions.md
  docs/conf.py
  docs/guides.rst
  docs/howtos.md
  docs/index.rst
  docs/project_overview.md
  examples/llamator-api.ipynb
  examples/llamator-langchain-custom-attack.ipynb
  examples/llamator-selenium.ipynb
  examples/llamator-telegram.ipynb
  examples/llamator-whatsapp.ipynb
  src/llamator/__version__.py
  src/llamator/attack_provider/run_tests.py
  src/llamator/attack_provider/util.py
  src/llamator/attacks/aim.py
  src/llamator/attacks/complimentary_transition.py
  src/llamator/attacks/crecsendo.py
  src/llamator/attacks/ethical_compliance.py
  src/llamator/attacks/harmful_behavior_multistage.py
  src/llamator/attacks/linguistic.py
  src/llamator/attacks/logical_inconsistencies.py
  src/llamator/attacks/sycophancy.py
  src/llamator/attacks/system_prompt_leakage.py
  src/llamator/client/chat_client.py
  src/llamator/client/client_config.py
  src/llamator/report_generators/word_report_generator.py
  tests/test_llamator.py
  tests/test_local_llamator.py
Labels: release

#98 add shuffle inconsistency attack
  CONTRIBUTING.md
  docs/attack_descriptions.md
  src/llamator/attack_provider/attack_loader.py
  src/llamator/attacks/attack_descriptions.json
  src/llamator/attacks/shuffle.py
  src/llamator/initial_validation.py
  src/llamator/main.py
  tests/test_llamator.py
  tests/test_local_llamator.py
Labels: enhancement

#99 add langchain client to langchain example and add telegram api info link
  .gitignore
  CONTRIBUTING.md
  README.md
  docs/attack_descriptions.md
  docs/conf.py
  docs/howtos.md
  docs/project_overview.md
  examples/.env.example
  examples/llamator-api.ipynb
  examples/llamator-langchain-custom-attack.ipynb
  examples/llamator-selenium.ipynb
  examples/llamator-telegram.ipynb
  examples/llamator-whatsapp.ipynb
  src/llamator/attacks/attack_descriptions.json
  tests/.env.example
  tests/test_local_llamator.py
Labels: documentation
